version: '3.5'

services:
  bigdata_db: 
    image: postgres:17.4
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    volumes:
      - bigdata_volume:/data/postgres

volumes:
  bigdata_volume: